CREATE TABLE IF NOT EXISTS endpoint_hit (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                         app varchar(100) NOT NULL,
                         uri varchar(100) NOT NULL,
                         ip varchar(50) NOT NULL,
                         timestamp timestamp without time zone,
                         primary key (id)
);