DROP TABLE IF EXISTS users, categories, events, requests, compilations, events_compilations;

CREATE TABLE users (
                         user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         email varchar(300) unique not null,
                         name varchar(300) not null
);

CREATE TABLE categories
(
                        category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name varchar(100) unique not null
);
CREATE INDEX categories_name ON categories(name);

CREATE TABLE events
(
                        event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        annotation text not null,
                        description text not null,
                        paid boolean not null,
                        participant_limit integer not null,
                        request_moderation boolean not null,
                        state varchar,
                        title varchar not null,
                        created_on timestamp not null,
                        event_date timestamp not null,
                        published_on timestamp,
                        initiator bigint not null,
                        category bigint not null,
                        views bigint,
                        confirmed_requests bigint,
                        lat real not null,
                        lon real not null,
                        constraint events_to_category foreign key (category) references categories(category_id) on delete cascade,
                        constraint events_to_initiator foreign key (initiator) references users(user_id) on delete cascade
);
CREATE INDEX events_initiator ON events(initiator);
CREATE INDEX events_category ON events(category);
CREATE INDEX events_state ON events(state);

CREATE TABLE requests (
                       request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       event bigint not null,
                       requester bigint not null,
                       status varchar(50) not null,
                       created timestamp not null,
                       constraint requests_to_event foreign key (event) references events(event_id) on delete cascade,
                       constraint requests_to_user foreign key (requester) references users(user_id) on delete cascade
);
CREATE INDEX requests_requester ON requests(requester);
CREATE INDEX requests_event ON requests(event);

CREATE TABLE compilations (
                       compilations_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title varchar(100) unique not null,
                       pinned boolean not null
);

CREATE TABLE events_compilations (
    compilations_id bigint,
    event_id        bigint,
    primary key (compilations_id, event_id),
    constraint events_compilations_to_compilations foreign key (compilations_id) references compilations (compilations_id) on delete cascade,
    constraint events_compilations_to_events foreign key (event_id) references events (event_id) on delete cascade
);


