DROP TABLE IF EXISTS users;

CREATE TABLE users (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         app varchar(100) NOT NULL,
                         uri varchar(100) NOT NULL,
                         ip varchar(50) NOT NULL,
                         timestamp timestamp
);